### PR TITLE
feat(c/libuv): Add libuv missing funcs & refactor go func style

### PR DESCRIPTION
**Pull request by hackerchai**
Signed-off-by: hackerchai <i@hackerchai.com>

### CODE REVIEW

**Comment by xushiwei** [comment]
resolve conflict please

**Comment by hackerchai** [comment]
> resolve conflict please

resolved. @xushiwei @aofei @visualfc ready for review, thx.

**Comment by xushiwei** [comment]
ci is not passed.

**Comment by hackerchai** [comment]
> ci is not passed.

ci passed. ready for review. @xushiwei

**Pull request merged**
